---
- name: Create {{ docker_systemd_config_path }}
  file:
    state: directory
    path: "{{ docker_systemd_config_path }}"
  when: docker_use_proxy

- name: Create {{ docker_config_path }}
  file:
    state: directory
    path: "{{ docker_config_path }}"

- name: Drop Systemd Docker proxy configuration
  template:
    src: http-proxy.conf.j2
    dest: "{{ docker_systemd_config_path }}/http-proxy.conf"
  when: docker_use_proxy
  notify:
    - reload daemon
    - restart docker

- name: Drop Docker configuration
  template:
    src: daemon.json.j2
    dest: "{{ docker_config_path }}/daemon.json"
  notify: restart docker

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
