---
# tasks file for synehan.docker
- include_vars: "{{ ansible_os_family | lower }}.yml"

- include_tasks: preinstall.yml

- include_tasks: setup-{{ ansible_os_family | lower }}.yml

- include_tasks: config.yml
